// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyAuLcAXJdrcadZ2oGTmjyKRHKNNIkrRS8g',
    appId: '1:937908368778:web:29a650fc707fee8bad4473',
    messagingSenderId: '937908368778',
    projectId: 'chuck-norris-application',
    authDomain: 'chuck-norris-application.firebaseapp.com',
    storageBucket: 'chuck-norris-application.appspot.com',
    measurementId: 'G-ZKMLTEQ30Y',
  );

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDajTNX4me2JVs_PapFl5E5OMY2CAHmEXM',
    appId: '1:937908368778:android:64822d273084799cad4473',
    messagingSenderId: '937908368778',
    projectId: 'chuck-norris-application',
    storageBucket: 'chuck-norris-application.appspot.com',
  );
}
